name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
change-template: '- $TITLE (#$NUMBER)'
version-template: '$MAJOR.$MINOR'
template: |
  The release resolves several issues:

  $CHANGES
