CREATE TABLE COURSE_SETTINGS(
        ID BIGINT(19) PRIMARY KEY AUTO_INCREMENT,
        LANGUAGE VARCHAR(255),
        TESTING_LANGUAGE VARCHAR(255),
        TESTING_FRAMEWORK VARCHAR(255),
        COURSE_ID BIGINT(19)
);

INSERT INTO COURSE_SETTINGS (COURSE_ID, LANGUAGE, TESTING_LANGUAGE, TESTING_FRAMEWORK)
SELECT ID, LANGUAGE, TESTING_LANGUAGE, TESTING_FRAMEWORK FROM COURSE ORDER BY ID;

ALTER TABLE COURSE
ADD COLUMN SETTINGS_ID BIGINT(19);

ALTER TABLE COURSE
ADD FOREIGN KEY (SETTINGS_ID)
REFERENCES COURSE_SETTINGS(ID);

UPDATE COURSE c
SET SETTINGS_ID=(
  SELECT MAX(ID)
  FROM COURSE_SETTINGS s
  WHERE c.ID = s.COURSE_ID
);

ALTER TABLE COURSE_SETTINGS DROP COLUMN COURSE_ID;
