UPDATE CODE_STYLE_REPORT
SET GRADE = 0
WHERE GRADE = 'A';

UPDATE CODE_STYLE_REPORT
SET GRADE = 1
WHERE GRADE = 'B';

UPDATE CODE_STYLE_REPORT
SET GRADE = 2
WHERE GRADE = 'C';

UPDATE CODE_STYLE_REPORT
SET GRADE = 3
WHERE GRADE = 'D';

UPDATE CODE_STYLE_REPORT
SET GRADE = 4
WHERE GRADE = 'E';

UPDATE CODE_STYLE_REPORT
SET GRADE = 5
WHERE GRADE = 'F';