INSERT INTO COURSE_STATE_ACTIVATED_SERVICES
(COURSE_STATE_ID)
SELECT DISTINCT COURSE_STATE_ID FROM COURSE_STATE_ACTIVATED_SERVICES;

UPDATE COURSE_STATE_ACTIVATED_SERVICES
SET ACTIVATED_SERVICES = 0
WHERE ACTIVATED_SERVICES IS NULL;